### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by stk2008** [KrazyTheFox/Cataclysm-DDA-Map-Editor#6]
Terribly sorry to post this in the issue tracker but it says to run click jar file I see no jar file.

I am using win7 64bit how do I use this program?

Thanks so much in advance :)

**Comment by KrazyTheFox** [comment]
Right now, since the program is being actively developed and doesn't really work yet, there is no build of it. You'd need to build the software yourself to use it. Many of the recent updates to Cataclysm have made this entirely non-functional, which is something that I'm slowly fixing.

I'm glad there's interest in this project; it just won't be ready for some time still. When it is, there will be a .jar and .exe to run.

**Comment by stk2008** [comment]
Thanks for replying mate :)

I understand CDDA is moving so fast not that I am complaning...far from it :)

Thanks for your work towards this great game mate and I shall keep an eye open for any updates to this :)

**Comment by stk2008** [comment]
Hi mate I see you have been doing some work on the editor :).
Thanks for this looking forward to testing :)
